### ISSUE TITLE
Disable app grid on double swipe-up with touchpad (on wayland or x11 + touchegg)

### ISSUE THREAD

**Issue by mijorus** [pop-os/gnome-shell#105]
Hi  there,
if I swipe up twice on pop os 22.04 with the trackpag I can access the old gnome app grid:
![image](https://user-images.githubusercontent.com/39067225/167633504-d35ec0d6-93c0-43b7-b862-094d58ef93a5.png)

which is probably not supposed to be seen.

Could you disable that in some way?
Thanks

**Comment by leviport** [comment]
Looks like the same behavior as https://github.com/pop-os/cosmic/issues/300

**Comment by mijorus** [comment]
absolutely, feel free mark this as duplicate and close it if needed

**Comment by leviport** [comment]
Yeah let's consolidate into https://github.com/pop-os/cosmic/issues/300, just so everything is in one place. Can you comment on that issue describing the touchpad gesture you do to induce the bug? I tried swiping around a bit on my touchpad and I couldn't seem to make it happen.
