### ISSUE TITLE
Show launcher, show workspaces and show applications icons in dock don't change text based on system language.

### ISSUE THREAD

**Issue by YoriMirus** [pop-os/gnome-shell#115]
### Affected version
Any POP!_OS version I tried (22.04, 21.10, 21.04)
### Bug summary
When having system language set to Czech, icons for "show launcher", "show applications" and "show workspaces" have english text, despite czech translation being present.

The rest of the system seems to be translated properly.

I tried setting my language to German and the icons still use English so this is not a language-specific issue.

### Steps to reproduce
1. Make sure system is up to date
2. Install and update Czech language in system settings
3. Set system language to Czech
4. Reboot

### What happened
Czech translations for the "show launcher", "show applications" and "show workspaces" did not appear.

### What did you expect to happen
Czech translations for the "show launcher", "show applications" and "show workspaces" to appear.

### Relevant logs, screenshots, screencasts etc.
Screenshots of the icons when system language is set to czech.
<img width="139" alt="image" src="https://user-images.githubusercontent.com/66534752/175398832-b587313c-9fd3-4693-a8ea-bcff59e7e3ca.png">
<img width="148" alt="image" src="https://user-images.githubusercontent.com/66534752/175399564-d1f15949-c367-4615-aae6-31fe419ec5fb.png">
<img width="145" alt="image" src="https://user-images.githubusercontent.com/66534752/175399615-a0486cbd-bd5d-4d20-a9b4-c143cc998268.png">

**Comment by n3m0-22** [comment]
Please review that these translations are correct. They should resolve the issue. Thank you for all your contributions.
https://github.com/pop-os/cosmic/pull/352/files

**Comment by YoriMirus** [comment]
Yes, these translations are correct. Glad to have been of help.
