### ISSUE TITLE
System menu: sound and screen brightness toggles do not respond to external input

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell#16]
System:
Pop!_OS 20.04
GNOME 3.36(ish)

Issue:
When booting a system, the sound and screen brightness toggles in the system menu are at the lowest levels even if that is not the case on the system itself. Changing the screen brightness or audio level with hotkeys on a laptop do not update the sliders in the system menu. Moving the sliders themselves will update the sliders and the specific setting as well.

![systemmenu](https://user-images.githubusercontent.com/7460774/77107537-74ba9180-69e6-11ea-8a06-22e5ab349be4.png)

**Comment by isantop** [comment]
Can confirm this on my machine as well.

**Comment by leviport** [comment]
It looks like this started working properly, can reopen if I'm wrong.
