### ISSUE TITLE
gnome-shell locks up(nvLock) on certain NVIDIA machines

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell#2]
On the GTX 1650 gaze14, when cold booting into NVIDIA mode, gnome-shell locks up for a couple of seconds on boot. The system also locks up when launching `nvidia-settings` from the applications menu.

The journald log related to this issue is:
` /usr/lib/gdm3/gdm-x-session: nvLock: client timed out, taking the lock`
![IMG_20190611_151614](https://user-images.githubusercontent.com/7460774/59308427-41c8bd80-8c5e-11e9-8592-0217e4040e4d.jpg)

This seems to have already been brought to people's attention upstream: https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-418/+bug/1825626

**Comment by brs17** [comment]
These lock ups can be reproduced quite consistently.

**Comment by mmstick** [comment]
I know that the GNOME Shell optimization patches fixed a good portion of these system locks when I was testing the gaze14 with the GTX 1650.

**Comment by brs17** [comment]
That is good to know @mmstick. I am running updates now and giving that a look now.

**Comment by brs17** [comment]
The updates do seem to fix the issues I was seeing (or at least eliminates them enough to make them not consistently reproducible). This means we need to build a new iso with these updates.
