### ISSUE TITLE
DE keeps crashing to login screen

### ISSUE THREAD

**Issue by JoeTheSane** [pop-os/gnome-shell#25]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Fresh Install of the NVIDIA image
Modified to use btrfs with @ and @home subvolumes

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Firefox
LibreOffice Writer

**Issue/Bug Description:**
Desktop Environment randomly crashes and sends me back to the login screen. Happens within a few minutes in Writer, happened once while running firefox. Only other app runnning is the default terminal

**Steps to reproduce (if you know):**
Run Writer and edit a document

**Expected behavior:**
DE does not crash

**Other Notes:**

**Comment by brs17** [comment]
Does this still happen for you? I have not experienced it on NVIDIA hardware. If this does continue to happen, please provide logs and we can reopen this issue.
