### ISSUE TITLE
Windows are always raised with mouse focus in 20.04

### ISSUE THREAD

**Issue by eternauta1337** [pop-os/gnome-shell#31]
When using Tweaks or dconf for focusing windows on hover or mouse over, windows are instantly raised, no matter if the raise windows option is disabled, or if a raise window delay is set.

This makes hover/mouse focus completely unusable, which is what I tend to use for higher productivity. Until this is fixed, I'm stuck with clicking on window to give them focus.

PS: Pop is awesome, so this wont keep me from using it. Pls fix tho!

**Comment by ajsantander** [comment]
Closing this in favor of https://github.com/pop-os/beta/issues/53

**Comment by leviport** [comment]
Thanks for reporting. We are tracking this one here https://github.com/pop-os/beta/issues/53
