### ISSUE TITLE
Certain applications can't be added to the dock

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gnome-shell#44]
Versions:

aaronh@pop-os:~$ uname -a
Linux pop-os 5.8.0-7625-generic #26~1603126178~20.10~210fe73-Ubuntu SMP Tue Oct 20 01:12:15 UTC  x86_64 x86_64 x86_64 GNU/Linux
(base) aaronh@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
aaronh@pop-os:~$ apt policy gnome-shell
gnome-shell:
  Installed: 3.38.1-1ubuntu1pop0~1603203664~20.10~f2c8ac6
  Candidate: 3.38.1-1ubuntu1pop0~1603203664~20.10~f2c8ac6
  Version table:
 *** 3.38.1-1ubuntu1pop0~1603203664~20.10~f2c8ac6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.38.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages

Steps to reproduce:

1. Open Caja (install it with 'sudo apt install caja' if needed)
2. Right click the icon on the dock to add it to favorites
3. Close the application
4. See that it is missing from the dock

Repeat the steps with this command/application:

system-config-printer

**Comment by ids1024** [comment]
`/usr/share/applications/system-config-printer.desktop` specifies `NotShowIn=KDE;GNOME;`. Removing this line makes it show in the launcher, add makes adding it to favorites work. Similarly, `/usr/share/applications/caja.desktop` has `NoDisplay=true` and `OnlyShowIn=MATE;`.

It appears that when a `.desktop` file specifies it shouldn't be shown, Gnome hides it from the favorites, but still shows "Add to Favorites".

**Comment by ids1024** [comment]
Reproduced on Fedora Rawhide and reported upstream: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3342

**Comment by ids1024** [comment]
Fixed upstream in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1488, which should be included in the next point release of Gnome Shell.

**Comment by ids1024** [comment]
Gnome Shell 3.38.2 seems to have a backport of that commit. Closing.
