### ISSUE TITLE
Hard lag when scrolling apps menu with touchpad

### ISSUE THREAD

**Issue by jawadalkassim** [pop-os/gnome-shell#58]
Scrolling with mouse wheel is smooth but when scrolling with two fingers up and down
it's stuck between, and I have to swipe multiple times to get the second page 
Happens both in Wayland and X11
even with all extensions disabled

https://user-images.githubusercontent.com/48631694/113056473-80719400-91b4-11eb-9fe6-9364c899355a.mp4

**Comment by bflanagin** [comment]
@jawadalkassim: Looks like you have a pretty heavily modified desktop setup. Could you give us more info on your setup.

Use this as a template:

* Version of Pop!_OS:
* Version of Gnome:
* Installed and enabled extensions: 
* Computer hardware:
   * CPU:
   * GPU:
   * Memory:

**Comment by jawadalkassim** [comment]
@bflanagin    
 Version of Pop!_OS: 20.10
    Version of Gnome: 3.38.3
    Installed and enabled extensions:
1: Top Panel Workspace Scroll
2:User themes
3: Dash to Panel / Dash to Dock
and Default Pop OS Extensions
    Computer hardware:
        CPU: Intel® Core™ i5-8250U CPU @ 1.60GHz × 8 
        GPU: AMD® Iceland / Mesa Intel® UHD Graphics 620 (KBL GT2)
        Memory: 8 GiB

**Comment by jawadalkassim** [comment]
@bflanagin  this issue still happening in COSMIC , With Balanced and Battery Life Modes,
