### ISSUE TITLE
Tap-to-click taps don't always work, physical mouse buttons do

### ISSUE THREAD

**Issue by echosa** [pop-os/gnome-shell#59]
I'm having an issue where tap-to-click taps don't always work as clicks. This issue exists for pretty much anything in the top bar (application menu, system tray/menu, app indicators, etc). 

For example, here's me using the physical mouse buttons on my laptop to access the power menu:

![physical-click-2021-04-05_11 02 02](https://user-images.githubusercontent.com/133786/113595665-ee77ea00-95fe-11eb-934b-bceaa13ab761.gif)

And here's what happens when I try with tap-to-click:

![tap-to-click-2021-04-05_11 02 40](https://user-images.githubusercontent.com/133786/113595687-f8015200-95fe-11eb-8679-a6f8e05f23ea.gif)

I've noticed other click/tap discrepancies, too. For instance, if I right-click a title bar (like Mattermost's), I get a menu:

![right-click-titlebar-2021-04-05_11 07 55](https://user-images.githubusercontent.com/133786/113596289-b91fcc00-95ff-11eb-9039-2c8718e40dd5.gif)

If I use a double-tap instead of physical right-click, nothing happens:

![two-finger-tap-titlebar-2021-04-05_11 08 35](https://user-images.githubusercontent.com/133786/113596335-c89f1500-95ff-11eb-88b2-a2b59edf76f8.gif)

I'm using a previous generation Darter Pro (darp5) with these specs:
![image](https://user-images.githubusercontent.com/133786/113596456-f2f0d280-95ff-11eb-97aa-b383e032f339.png)

The only GNOME extensions I have enabled are:
- [Notification Counter](https://extensions.gnome.org/extension/1386/notification-counter/)
- [Sound Input & Output Device Chooser](https://extensions.gnome.org/extension/906/sound-output-device-chooser/)
- Ubuntu AppIndicators (built-in)

The issue persists even when I disable all extensions.

For the record, I asked about this in main GNOME IRC channel, thinking it was a GNOME issue. They said it is likely a Pop!_OS issue, which is why I'm reporting this here.

```
<echosa> Hello, all! Hopefully this is the right channel for this. Got a weird issue I'm hoping someone can at least help me understand, if not fix. GNOME 3.38.3 on Pop!_OS 20.10. Tap-to-click doesn't activate top bar sub-menus. What I mean is: if I click on the system menu area (battery, wifi, etc) then try to click on, say, Power Off / Log Out, the behavior changes between click and tap.
<echosa> If I'm clicking the physical left mouse button on my laptop, the power menu opens. If I use tap-to-click and and tap on Power Off / Log Out, it highlights then closes the entire system menu. I don't even know where to begin looking or debugging.
<echosa> FTR - I have similar discrepancies elsewhere. Example: right-clicking application title bars. Physical right mouse button works all the time, but two-finger tap often (depending on the app) doesn't open the context menu.
<alatiera> echosa file a bug against popos
<oxylibrium[m]> ^^ yeah, I'd recommend filing a bug against PopOS first; and they'll escalate it to GNOME if needed
<alatiera> its likely something on their end given their are patched to the bone
<echosa> Is there a way to know that it is pop specific? Alternatively, is there a way to test/debug the issue myself?
<echosa> I'm fine filing an issue with pop, of course, and I will. That said, I'm trying to use this as a bit of a learning experience, if possible, which is why I'd like to know more about how to dig into it. :-)
<oxylibrium[m]> Unfortunately since Pop's GNOME is, afaik, heavily patched/extended, its difficult to know where GNOME ends and PopGNOME begins unless you're at least cursorily familiar with the code
```

**Comment by jacobgkau** [comment]
> I'm using a previous generation Darter Pro (darp5) with these specs:

I'm sorry about the touchpad trouble! For System76 hardware, it's best to open a [support ticket](http://support.system76.com/) so our support team can help diagnose if this is software, hardware, or configuration.

How long ago did this issue start? If you boot into Pop Recovery by holding down the spacebar during boot, does the issue also occur there? In Settings -> Mouse & Touchpad, is `Tap to Click` enabled? If you install GNOME Tweaks (`sudo apt install gnome-tweaks`) and open that app, in the Keyboard & Mouse section, what is the `Mouse Click Emulation` setting set to? (The default is `Fingers`.)

To address the comments from IRC that this is Pop!_OS-specific, you could try a live disk of another GNOME distribution such as Fedora and see if the issue also occurs there. If it does, then this might be something to do with your touchpad or with upstream GNOME; if it doesn't, that would point more towards something being shipped in Pop.

**Comment by echosa** [comment]
> How long ago did this issue start?

I don't know. I had tap-to-click turned off almost since I bought the machine a couple of years ago. I just recently started trying to use tap-to-click again, and noticed these issues.

> If you boot into Pop Recovery by holding down the spacebar during boot, does the issue also occur there? 

It does not! The taps seems to work find in the top bar when I'm in recovery.

> In Settings -> Mouse & Touchpad, is Tap to Click enabled? If you install GNOME Tweaks (sudo apt install gnome-tweaks) and open that app, in the Keyboard & Mouse section, what is the Mouse Click Emulation setting set to? (The default is Fingers.)

It is set to "Fingers".

**Comment by echosa** [comment]
Ah, it also works with a new user account. So some setting or config in my account is causing the issue. I have no idea how to triage it to find out.

**Comment by echosa** [comment]
Apparently, this is a known issue with having tap-to-drag disabled. https://gitlab.gnome.org/GNOME/mutter/-/issues/1706
