### ISSUE TITLE
Disable Window Re-Org when the Applications Panel is Opened.

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-shell#70]
Though not a fix for https://github.com/pop-os/cosmic/issues/88, it's the intended behavior when Applications is opened.

**Comment by ids1024** [comment]
Just disabling the zooming, windows appear in the same places, but are draggable like in the workspaces overview. Presumably not quite what we want (also the dock appears on the second monitor, which seems a bit odd).

Exactly what is the desired behavior for interacting with additional monitors? No interaction? Clicking anywhere on the second monitor closes the overview?

**Comment by jackpot51** [comment]
@ids1024 I think your intuition is right. It should be similar to when the Launcher is open

**Comment by ids1024** [comment]
Yeah, I was thinking it should match the behavior of the launcher.

**Comment by ids1024** [comment]
Implemented in https://github.com/pop-os/cosmic/pull/116.
