### ISSUE TITLE
upstream pop-dark-theme.patch 

### ISSUE THREAD

**Issue by Muqtxdir** [pop-os/gnome-shell#77]
Hi 👋

I've always loved Pop!_OS's ability to switch both GTK and gnome-shell theme simultaneously without the need of user-themes gnome-shell-extension. I'd be helpful if the [`pop-dark-theme.patch`](https://github.com/pop-os/gnome-shell/blob/master_impish/debian/patches/pop-dark-theme.patch) be upstreamed so that Ubuntu's [Yaru](https://github.com/ubuntu/yaru) could also benefit from this on ubuntu-desktop session. I filed the bug [LP: #1943857](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1943857) with the patch on Launchpad and it was suggested to me that I should open an MR [here](https://salsa.debian.org/gnome-team/gnome-shell/-/tree/ubuntu/master).

I request the concerned devs behind this patch to open MR instead of me as it should be credited to their name for their contribution.

Thanks!

**Comment by jackpot51** [comment]
Sounds good, I will make a PR

**Comment by jackpot51** [comment]
I wanted to provide an update. My salsa.debian.org account requires administrator approval at this time.

**Comment by Muqtxdir** [comment]
> My salsa.debian.org account requires administrator approval at this time.

thanks for the update, I don't know whether the MR would be merged for 21.10 as it's way beyond Freeze date. (_sorry mistake on my part should have known better when's the Freeze date for the release_)

**Comment by jackpot51** [comment]
I'm still waiting. I don't really see a reason the change has to come from me or be attributed to me. If Ubuntu is interested, they can feel free to copy the patch.

**Comment by Muqtxdir** [comment]
Thanks for the permission, I'll create MR with patch 👍
