### ISSUE TITLE
19.10: Top left corner of Activities bar is not selectable

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-shell#9]
In 19.10, the top left pixel (moving the mouse all the way to the top left of the screen), is no longer a valid spot to click the `Activities` button.

This seems to be an upstream issue, potentially this: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1601

**Comment by 1h5w** [comment]
Following
> [https://gitlab.gnome.org/GNOME/gnome-shell/issues/1601](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1601) ,

this turns out to be a Clutter issue found here: [https://gitlab.gnome.org/GNOME/mutter/issues/893](https://gitlab.gnome.org/GNOME/mutter/issues/893) and the fix is already merged in the latest commit upstream.
