### ISSUE TITLE
22.04: Opening USB drives in Nautilus crashes Gnome Shell

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-shell#90]
Steps to reproduce: 
1. During a user session, plug in a USB drive
2. Open Nautilus
3. Click on the USB drive in the sidebar on the left
4. Gnome Shell will crash and end up at the "Oh no! Something has gone wrong." screen with a "Log out" screen.

`cd`ing into the drive and running `nautilus .` also crashes Gnome Shell.

**Comment by wagnerck** [comment]
Can confirm this happens under a `virt-manager` VM with an attached ISO image as well. The same thing occurs when clicking on the drive in the dock, too (as it launches Nautilus).

`dmesg` shows a segfault by GNOME shell in `libglib`:
```
[  882.864308] show_signal_msg: 19 callbacks suppressed
[  882.864316] gnome-shell[2537]: segfault at 0 ip 00007f2a06e54414 sp 00007ffc4
ffc22e8 error 4 in libglib-2.0.so.0.7200.0[7f2a06e39000+8f000]
[  882.864325] Code: 84 00 00 00 00 00 44 8b 04 87 e9 47 ff ff ff 0f 1f 80 00 00
 00 00 f3 0f 1e fa 89 f8 c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <0f> be 17 b8 05 15 00 00 84 d2 74 18 89 c1 48 83 c7 01 c1 e1 05 01
[  884.281830] gnome-shell[4194]: segfault at 0 ip 00007fa0b28b4414 sp 00007fff85851ba8 error 4 in libglib-2.0.so.0.7200.0[7fa0b2899000+8f000]
[  884.281839] Code: 84 00 00 00 00 00 44 8b 04 87 e9 47 ff ff ff 0f 1f 80 00 00 00 00 f3 0f 1e fa 89 f8 c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <0f> be 17 b8 05 15 00 00 84 d2 74 18 89 c1 48 83 c7 01 c1 e1 05 01
[  885.609045] gnome-shell[4255]: segfault at 0 ip 00007f18f72c4414 sp 00007fff5b2b57a8 error 4 in libglib-2.0.so.0.7200.0[7f18f72a9000+8f000]
[  885.609053] Code: 84 00 00 00 00 00 44 8b 04 87 e9 47 ff ff ff 0f 1f 80 00 00 00 00 f3 0f 1e fa 89 f8 c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <0f> be 17 b8 05 15 00 00 84 d2 74 18 89 c1 48 83 c7 01 c1 e1 05 01
[  886.863219] gnome-shell[4305]: segfault at 0 ip 00007fdea21d5414 sp 00007ffffcb982d8 error 4 in libglib-2.0.so.0.7200.0[7fdea21ba000+8f000]
[  886.863228] Code: 84 00 00 00 00 00 44 8b 04 87 e9 47 ff ff ff 0f 1f 80 00 00 00 00 f3 0f 1e fa 89 f8 c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <0f> be 17 b8 05 15 00 00 84 d2 74 18 89 c1 48 83 c7 01 c1 e1 05 01
```

**Comment by ids1024** [comment]
These seems to happen if the cosmic-dock extension is enabled and not otherwise, so something there must be causing it.

**Comment by ghost** [comment]
> These seems to happen if the cosmic-dock extension is enabled and not otherwise, so something there must be causing it.

I also get logged out if I click on the drive's icon in the dock. Disabling "show mounted drives" in Cosmic dock's settings stops this from occurring and also stops the problem in Nautilus.

**Comment by ids1024** [comment]
This is probably fixed upstream in https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock, but rebasing the cosmic-dock changes on that is non-trivial.

**Comment by ids1024** [comment]
This should be addressed once the work in https://github.com/pop-os/cosmic-dock/pull/124 is done.
