### ISSUE TITLE
Focus being stolen when showing desktop

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/gnome-shell#91]
Some background application is stealing focus from the active window after booting the computer. On every boot.

This is most obvious after installing Pop!_OS
1. Install Pop, and get to gnome-initial-setup
2. Don't touch anything. 
3. Focus will be lost from gnome-initial-setup

Though it also effects each boot, the best example I can find is
1. Reboot computer
2. Very quickly after you can see the desktop, open the launcher
3. After a brief moment the launcher will lose focus.

**Comment by XV-02** [comment]
This effects every login, including resuming a session in progress, from the gdm login screen.

**Comment by leviport** [comment]
After installing the latest debug iso (number 54), it looks like GIS keeps focus. Can anyone else confirm?

**Comment by XV-02** [comment]
Can confirm across multiple installs that GIS retains focus with newest debug. Focus also retained in live session by installer, and the aforementioned focus loss when the launcher is launched just after boot or log-in is also no longer present.

I am closing this as it appears resolved in Debug 54, which will represent the second Beta release.
